config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects do
    resources :comments
  end
  devise_for :users
  get '', to: redirect('/projects')
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :comments

  enum status: { active: 'active', completed: 'completed', archived: 'archived' }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.create(params[:comment].permit!.merge(user: current_user))

    respond_to do |format|
      format.html { redirect_to @project, notice: 'Comment was successfully created.' }
      format.json { render :show, status: :created, location: @project }
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project = Project.where(id: params[:id]).includes(comments: :user).first
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.status != project_params[:status]
        message = "Change status from #{@project.status} to #{project_params[:status]}"
        @project.comments.create(comment: message, user: current_user)
      end

      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <span><%= comment.user.email %>: </span> </br>
    &emsp;
    <%= comment.comment %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@project, @project.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit 'Add Comment' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeyConversation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
    <% if user_signed_in? %>
      <nav>
          <ul>
              
              <li><%= link_to "Sign out", destroy_user_session_path%></li>
              <li><%= link_to "Projects", projects_path%></li>
          </ul>
      </nav>
    <% end %>

    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red; margin-bottom: 20px;">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="margin-bottom: 15px;">
    <%= form.label :name, "Project Name", class: "form-label" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter project name" %>
  </div>

  <div style="margin-bottom: 15px;">
    <%= form.label :status, "Status", class: "form-label" %>
    <%= form.select :status, Project.statuses.map { |k, v| [k, v] }, class: "form-select" %>
  </div>

  <div>
    <%= form.submit "Save Project", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= project.status %>
  </p>

</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projects" %>

<h1 style="text-align: left;">Projects</h1>

<p>
  <%= link_to "New project", new_project_path, class: "button" %>
</p>

<table id="projects-table" style="width: 100%; border-collapse: collapse;">
  <thead>
    <tr>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Project Name</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Status</th>
      <th style="border: 1px solid #ddd; padding: 8px; width: 150px;">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td style="border: 1px solid #ddd; padding: 8px; text-align: left;"><%= project.name %></td>
        <td style="border: 1px solid #ddd; padding: 8px; text-align: left;"><%= project.status %></td>
        <td style="border: 1px solid #ddd; padding: 8px; text-align: center;">
          <%= link_to "Show", project, style: "margin-right: 5px;" %>
          <%= link_to 'Edit', edit_project_path(project) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green;"><%= notice %></p>

<div class="project-details">
  <%= render @project %>

  <div class="project-actions" style="margin-bottom: 20px;">
    <%= button_to "Edit this project", edit_project_path(@project), method: :get %> </br>
    <%= button_to "Back to projects", projects_path, method: :get %>  </br>
    <%= button_to "Destroy this project", @project, method: :delete, data: { confirm: "Are you sure you want to delete this project?" } %>
  </div>

  <hr>

  <div class="project-history">
    <h2>History</h2>
    <%= render @project.comments %>

    <hr>
    <h3>Add a Comment</h3>
    <%= render "comments/form" %>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>